#!/bin/bash

# update working tree
cd {{cirrus_dir}}/{{app}}
unset GIT_DIR
# save last commit
LAST_COMMIT=`git log -1 | awk 'NR==1 {print $2}'`
# this is basiclly a force pull
# so even if you force pushed this can still work
git fetch --all
git reset --hard origin/main

handle_error() {
  echo "`tput setaf 1`ERROR: Command $1 exited with code $2, working tree is reverted.`tput sgr0`"
  git reset $LAST_COMMIT --hard
	exit $2
}

cirrus deploy {{app}}

# {{commands}}
# 
# cirrus stop {{app}}
# cirrus start {{app}}
